export interface Order {
    id?: number; // Optional since it is auto-generated
    orderDate?: string; // Optional if generated by the backend
    totalPrice?: number;
    customerName: string;
    phoneNumber: string;
    deliveryAddress: string;
    userId?: string; // Assuming 'user' is mapped to a User entity
    paymentMethod: string;
}
